# -*- coding: utf-8 -*-
"""Predictive_Maintenace_cluster_and_anomalies_detection - OCT 2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kblzMNuTmtnZ20FBx61EZIz7QPv_IKvE

##**Predictive Maintenance ANOMALY DETECTION WITH PYOD**

#IMPORTING PYOD AND DATA SET
"""

#code snippet 1
#Installing pyod package for anormaly detection algorithms (knn)
!pip install pyod

#code snippet 2
#Importing pyod
from pyod.models.knn import KNN

# Code snippet 3
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/Imjuandiaz/MTTF-Predictive-Maintenance-analysis/refs/heads/main/Data/ai4i2020.csv')


data

# Code snippet 4
# Create new dataset with only numerical columns
numeric_dataset = data.select_dtypes(include=['float64', 'int64'])
numeric_dataset

# Code snippet 5
# Training with the KNN algorithm to identify the anomalies
ad_model = KNN()

# Handle missing values by imputing with the mean
numeric_dataset_cleaned = numeric_dataset.fillna(numeric_dataset.mean())

ad_model.fit(numeric_dataset_cleaned)

# Code snippet 6
#Predict anomalies (1 = normal, -1 = Anomaly)
anomaly_labels = ad_model.labels_
anomaly_scores = ad_model.decision_scores_

"""#ADDING LABEL TO ANOMALY LABEL AND SCORE

"""

# Code snippet 7
# Adding the anomaly results to the original dataframe
data['Anomaly_Label'] = anomaly_labels
data['Anomaly_Score'] = anomaly_scores
data

"""#IMPORTING DATA SET WITH ANOMALY COLUMNS"""

# Code snippet 8
# Exporting the dataset to a csv file with anomaly info
data.to_csv('Predictive_Maintenance_KNN_Anomalies.csv', index=False)

"""#TOTAL COUNT OF ANOMALY ON DATASET"""

# Code snippet 9
# Displaying the number of anomalies
num_anomalies = (data['Anomaly_Label'] == 1).sum()
print(f"Number of anomalies: {num_anomalies}")

"""##**Predictive Maintenance Clustering With h2o**

#IMPORTING H2O AND DATA SET
"""

#code snippet 1
#Installing h2o
!pip install h2o

#code snippet 2
#Importing h2o
import h2o

#initialize h2o
h2o.init()

# Code snippet 3
# Importing dataset
data = h2o.import_file('https://raw.githubusercontent.com/Imjuandiaz/MTTF-Predictive-Maintenance-analysis/refs/heads/main/Data/ai4i2020.csv')


data

#code snippet 4
#Importing Kmeans Estimator
from h2o.estimators.kmeans import H2OKMeansEstimator

#code snippet 5
#setting the number of clusters in the data train as 2
kmeans_model = H2OKMeansEstimator(k=2)

#Train the clustering model
kmeans_model.train(training_frame=data)

#code snippet 6
#Displaying the cluster size
kmeans_model.size()

# Code Snippet 7
# Import libraries
import pandas as pd

# Predict clusters for each row
pred = kmeans_model.predict(data)

# Join prediction to the original dataset
data_with_clusters = data.cbind(pred)

# Convert to pandas DataFrame
df = data_with_clusters.as_data_frame()

# Clean column names to remove any invisible characters (like BOM)
df.columns = df.columns.str.strip().str.replace('\ufeff', '')

# ==========================
# Numeric variables (según tu dataset)
# ==========================
numeric_cols = [
    "UDI",
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
    "Machine failure",
    "TWF",
    "HDF",
    "PWF",
    "OSF",
    "RNF"
]

numeric_summary = df.groupby("predict")[numeric_cols].mean()

# ==========================
# Categorical variables (según tu dataset)
# ==========================
categorical_cols = [
    "Product ID",
    "Type"
]

categorical_summary = {}
for col in categorical_cols:
    categorical_summary[col] = (
        df.groupby("predict")[col]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
    )

# ==========================
# Code Snippet 8
# ==========================
# Combine summaries
# ==========================

# Merge all categorical summary DataFrames into a single one
categorical_df = pd.concat(categorical_summary.values(), axis=1)

# Combine with numeric summary
cluster_profiles = numeric_summary.join(categorical_df, how="left")

# Export to CSV
cluster_profiles.to_csv("Predictive_Maintenance_cluster_profiles.csv", index=True)

# Display in console
print(cluster_profiles)